version: '3'
services:
  nginx:
    image: nginx:1.13.3
    volumes:
      - ./docker/nginx/conf:/etc/nginx
      - .:/var/www/application
    networks:
      app_network:
        aliases:
          - api.dev
    ports:
      - "127.0.0.146:80:80"

  nginx-menu:
    image: nginx:1.13.3
    volumes:
      - ./docker/nginx/menu-conf:/etc/nginx
      - .:/var/www/application
    networks:
      app_network:
        aliases:
          - api.dev
    ports:
      - "127.0.0.200:80:80"

  phpfpm:
    build: docker/php-fpm
    networks:
      app_network:
        aliases:
          - api.dev
    volumes:
      - ./docker/php-fpm/etc:/usr/local/php/etc
      - ./docker/php-fpm/etc/php.ini:/etc/php.ini
      - .:/var/www/application
      - ~/.ssh:/root/.ssh
      - ./logs:/var/www/logs


  mongo:
    image: mongo:4.2
    networks:
      app_network:
        aliases:
          - api.dev
    volumes:
      - ./docker/mongo/data:/data/db
      - .:/var/www/application
    ports:
      - "127.0.0.146:27017:27017"

networks:
  app_network:
    driver: bridge
