version: '3'
services:
  nginx:
    image: nginx:1.13.3
    volumes:
      - ./docker/nginx/conf:/etc/nginx
      - .:/var/www/application
    networks:
      app_network:
    ports:
      - "127.0.0.139:80:80"

  phpfpm:
    build: docker/php-fpm
    networks:
      app_network:
    volumes:
      - ./docker/php-fpm/etc:/usr/local/php/etc
      - ./docker/php-fpm/logs:/tmp/symfony/logs
      - ./docker/php-fpm/cache:/tmp/symfony/cache/dev
      - .:/var/www/application
      - ~/.ssh:/root/.ssh
      - ./logs:/var/www/logs


  mongo:
    image: mongo:4.2
    networks:
      app_network:
    volumes:
      - ./docker/mongo/data:/data/db
      - .:/var/www/application
    ports:
      - "127.0.0.139:27017:27017"

  mysql:
     image: mysql:5.7
     networks:
       app_network:
     environment:
       MYSQL_DATABASE: 'api'
       # So you don't have to use root, but you can if you like
       MYSQL_USER: 'api'
       # You can use whatever password you like
       MYSQL_PASSWORD: 'api'
       # Password for root access
       MYSQL_ROOT_PASSWORD: 'api'
     volumes:
       - ./docker/mysql/data:/data/db
     ports:
       - "127.0.0.136:3306:3306"

networks:
  app_network:
    driver: bridge
