version: '3.8'
services:
  nginx:
    container_name: dsign-ngnix
    image: nginx:1.13.3
    environment:
      SERVER_NAME: api-dev.ds-ign.it
    volumes:
      - ./docker/nginx/conf:/etc/nginx
      - .:/var/www/application
    networks:
      app_network:
        aliases:
          - api
    ports:
      - "80:80"

  phpfpm:
    container_name: dsing-php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile8.3
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    networks:
      app_network:
        aliases:
          - api
    volumes:
      - ./docker/php-fpm/etc:/usr/local/php/etc
      - .:/var/www/application
      - ~/.ssh:/root/.ssh
      - ./logs:/var/www/logs


  mongo:
    container_name: dsign-mongo
    image: mongo:6
    networks:
      app_network:
        aliases:
          - api
    volumes:
      - ./docker/mongo/data:/data/db
      - .:/var/www/application
    ports:
      - "27017:27017"

networks:
  app_network:
    driver: bridge