<?php
declare(strict_types=1);

namespace App\Module\Restaurant\Storage\Adapeter\Mongo;

use App\Storage\Adapter\Mongo\MongoAdapter;
use MongoDB\BSON\ObjectId;

/**
 * Class MenuMongoAdapter
 * @package App\Module\Restaurant\Storage\Adapeter\Mongo
 */
class MenuMongoAdapter extends MongoAdapter {

    /**
     * @param array $search
     * @param null $limit
     * @param null $skip
     * @return \MongoCursor
     * @throws \MongoCursorException
     * @throws \MongoException
     */
    protected function searchDataSource(array $search, $limit = null, $skip = null) {

        foreach ($search as $key => &$value) {

            switch ($key) {
                case 'organizations':
                    $ids = [];
                    foreach ($value as $id) {
                        array_push($ids, new ObjectId($id));
                    }
                    $search['organization._id'] = ['$in' => $ids];
                    unset($search[$key]);
                    break;
            }
        }

        return parent::searchDataSource($search, $limit, $skip); // TODO: Change the autogenerated stub
    }
}